const aeroportos = {
  // --- Brasil (principais) ---
  GRU: "São Paulo – Guarulhos",
  CGH: "São Paulo – Congonhas",
  VCP: "Campinas – Viracopos",
  GIG: "Rio de Janeiro – Galeão",
  SDU: "Rio de Janeiro – Santos Dumont",
  BSB: "Brasília",
  SSA: "Salvador",
  REC: "Recife",
  FOR: "Fortaleza",
  BEL: "Belém",
  VIX: "Vitória",
  CWB: "Curitiba",
  FLN: "Florianópolis",
  MAO: "Manaus",
  NAT: "Natal",
  POA: "Porto Alegre",
  SLZ: "São Luís",
  CNF: "Belo Horizonte – Confins",
  AJU: "Aracaju",
  MCZ: "Maceió",
  JPA: "João Pessoa",
  GYN: "Goiânia",

  // --- EUA (hubs + destinos comuns) ---
  JFK: "New York – JFK",
  LGA: "New York – LaGuardia",
  EWR: "Newark",
  IAH: "Houston",
  ORD: "Chicago – O'Hare",
  ATL: "Atlanta",
  DEN: "Denver",
  SEA: "Seattle",
  LAS: "Las Vegas",
  DTW: "Detroit",
  BOS: "Boston",
  MIA: "Miami",
  FLL: "Fort Lauderdale",
  MCO: "Orlando",
  PHX: "Phoenix",
  CLT: "Charlotte",
  MSP: "Minneapolis – St. Paul",
  MSY: "New Orleans – Louis Armstrong",
  BNA: "Nashville",
  PIT: "Pittsburgh",
  CLE: "Cleveland",
  RDU: "Raleigh – Durham",
  SLC: "Salt Lake City",
  TPA: "Tampa",
  STL: "St. Louis",
  IND: "Indianapolis",
  CVG: "Cincinnati",
  BWI: "Baltimore – Washington",
  MCI: "Kansas City",
  MEM: "Memphis",
  RNO: "Reno",
  PDX: "Portland",
  SFO: "San Francisco",
  SJC: "San Jose",
  OAK: "Oakland",
  SAN: "San Diego",
  LAX: "Los Angeles",
  SNA: "Santa Ana",
  SMF: "Sacramento",
  SDF: "Louisville",
  BDL: "Hartford",
  RIC: "Richmond",
  OKC: "Oklahoma City",
  IAD: "Washington – Dulles",
  DCA: "Washington – National",
  DFW: "Dallas – Fort Worth",
  AUS: "Austin",  
  PHL: "Philadelphia",
  CMH: "Columbus",
  
  // --- Canadá ---
  YYZ: "Toronto – Pearson International",
  YUL: "Montreal – Trudeau International",
  YVR: "Vancouver – International",
  YYC: "Calgary – International",
  YEG: "Edmonton – International",
  YOW: "Ottawa – International",
  YWG: "Winnipeg – International",
  YHZ: "Halifax – Stanfield International",
  YYT: "St. John's – International",
  YQB: "Quebec City – Jean Lesage International",
  
  // --- México / América Central / Caribe ---
  MEX: "Mexico City",
  CUN: "Cancún",
  SJD: "Los Cabos",
  GDL: "Guadalajara",
  MTY: "Monterrey",
  SLP: "San Luis Potosí",
  SJO: "San José",
  HAV: "Havana",
  SNU: "Santa Clara",
  OAX: "Oaxaca - México",

  // --- América do Sul ---
  SCL: "Santiago",
  EZE: "Buenos Aires – Ezeiza",
  AEP: "Buenos Aires – Aeroparque",
  EZE: "Buenos Aires – Ezeiza",
  LIM: "Lima",
  GYE: "Guayaquil",
  UIO: "Quito",
  ASU: "Asunción",
  MVD: "Montevideo",
  BOG: "Bogotá",
  MDE: "Medellín",
  CTG: "Cartagena",
  CUZ: "Cusco",
  MDZ: "Mendoza",
  SJO: "San José",
  PTY: "Panama City – Tocumen",
  BIL: "Billings - Montana",
  
  // --- Europa ---
  MAD: "Madrid",
  BCN: "Barcelona",
  LIS: "Lisbon",
  OPO: "Porto",
  CDG: "Paris – Charles de Gaulle",
  ORY: "Paris – Orly",
  AMS: "Amsterdam",
  BRU: "Brussels",
  ZRH: "Zurich",
  VIE: "Vienna",
  HEL: "Helsinki",
  OSL: "Oslo – Gardermoen",
  CPH: "Copenhagen",
  DUB: "Dublin",
  WAW: "Warsaw",
  FRA: "Frankfurt",
  MUC: "Munich",
  BER: "Berlin – Brandenburg",
  PRG: "Prague",
  ATH: "Athens",
  GVA: "Geneva",
  NCE: "Nice",
  MRS: "Marseille",
  FCO: "Rome – Fiumicino",
  VCE: "Venice – Marco Polo",
  LIN: "Milan – Linate",
  MXP: "Milan – Malpensa",
  LHR: "London – Heathrow",
  LGW: "London – Gatwick",
  STN: "London – Stansted",
  LCY: "London – City",
  LTN: "London – Luton",
  MAN: "Manchester",
  EDI: "Edinburgh",
  GLA: "Glasgow",
  VRN: "Verona",
  KRK: "Kraków",
  CGN: "Cologne",
  DUS: "Düsseldorf",
  HAM: "Hamburg",
  NAP: "Naples",
  ARN: "Stockholm – Arlanda",
  LYS: "Lyon",
  BGI: "Bridgetown - Barbados",
  VLC: "Valencia",
  SVQ: "Sevilla - Espanha",
  BOD: "Bordeaux - França",
  
  // --- Oriente Médio / África ---
  IST: "Istanbul",
  TLV: "Tel Aviv",
  DOH: "Doha",
  AUH: "Abu Dhabi",
  DXB: "Dubai",
  JNB: "Johannesburg",
  ADD: "Addis Ababa",
  CAI: "Cairo",
  CMN: "Casablanca",
  CPT: "Cape Town",

  // --- Ásia / Oceania ---
  HND: "Tokyo – Haneda",
  NRT: "Tokyo – Narita",
  ICN: "Seoul – Incheon",
  SIN: "Singapore",
  KUL: "Kuala Lumpur",
  BKK: "Bangkok – Suvarnabhumi",
  DEL: "Delhi – Indira Gandhi",
  HKG: "Hong Kong",
  PVG: "Shanghai – Pudong",
  PEK: "Beijing – Capital",
  SYD: "Sydney", 
  PKX: "Beijing – Daxing",
  SZX: "Shenzhen",
  


};
